ARG IMAGE_ARCH
ARG IMAGE_DISTRO
ARG IMAGE_VERSION
ARG IMAGE_PLATFORM
FROM --platform=${IMAGE_PLATFORM} ${IMAGE_ARCH}/${IMAGE_DISTRO}:${IMAGE_VERSION}

ARG QEMU_FILE
ADD ${QEMU_FILE} /usr/bin

ARG RUN_CMD
ENV RUN_CMD ${RUN_CMD}
CMD ${RUN_CMD}
